services:
  dev:
    build:
      context: ./dev
    volumes:
      - .:/workspaces/taxos
    working_dir: /workspaces/taxos
    command: sleep infinity
    network_mode: service:backend
    depends_on:
      - backend
      - frontend

  backend:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - .:/workspaces/taxos
    working_dir: /workspaces/taxos/backend
    command: >
      bash -c "pip install -r requirements.txt &&
               pip install -r ../dev/requirements.txt &&
               python -m debugpy --listen 0.0.0.0:5678 api/connect_http_server.py"
    ports:
      - "5678:5678"
      - "50051:50051"

  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspaces/taxos
    working_dir: /workspaces/taxos/frontend
    command: >
      bash -c "npm install &&
               npm run dev"

    ports:
      - "5173:5173"
    environment:
      - VITE_GRPC_API_URL=http://localhost:50051
      - CHOKIDAR_USEPOLLING=true
