services:
  taxos-backend:
    container_name: taxos_backend
    image: ${REGISTRY_HOST}/taxos-backend:latest
    ports:
      - "50051:50051"
    environment:
      - PYTHONPATH=/app
    volumes:
      - /mnt/x/srv/taxos:/app/data
    restart: unless-stopped

  taxos-frontend:
    container_name: taxos_frontend
    image: ${REGISTRY_HOST}/taxos-frontend:latest
    ports:
      - "${UI_PORT:-80}:5173"
    environment:
      - VITE_GRPC_API_URL=http://htpc.lan:50051
    restart: unless-stopped
    depends_on:
      - taxos-backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
