services:
  backend:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - .:/workspaces/taxos
    command: >
      bash -c "pip install -r /workspaces/taxos/backend/requirements.txt &&
               pip install -r /workspaces/taxos/dev/requirements.txt &&
               python -m debugpy --listen 0.0.0.0:5678 /workspaces/taxos/backend/api/connect_http_server.py"
    ports:
      - "5678:5678"
      - "50051:50051"

  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspaces/taxos
    working_dir: /workspaces/taxos/frontend
    command: sleep infinity
    ports:
      - "5173:5173"
    environment:
      - VITE_GRPC_API_URL=http://localhost:50051
      - CHOKIDAR_USEPOLLING=true
