services:
  backend:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      - .:/workspaces/taxos
    command: sleep infinity
    ports:
      - "50051:50051"

  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspaces/taxos
    working_dir: /workspaces/taxos/frontend
    command: sleep infinity
    ports:
      - "5173:5173"
    environment:
      - VITE_GRPC_API_URL=http://localhost:50051
      - CHOKIDAR_USEPOLLING=true
