services:
  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspaces/taxos
    working_dir: /workspaces/taxos
    command: sleep infinity
    network_mode: service:backend
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspaces/taxos
    working_dir: /workspaces/taxos/backend
    ports:
      - "5678:5678"
      - "50051:50051"

  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    volumes:
      - .:/workspaces/taxos
    working_dir: /workspaces/taxos/frontend
    command: >
      bash -c "npm install &&
               npm run dev"
    ports:
      - "5173:5173"
    environment:
      - VITE_GRPC_API_URL=http://localhost:50051
